node {
   def commit_id
   stage('MyPreparation') {
     checkout scm
     sh "git rev-parse --short=9 HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
     print("#4307 | commit_id = " + commit_id)
   }
   stage('MyTest') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('MyDocker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("ik4307ik/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
